[tool.poetry]
name = "kusogaki_bot"
version = "0.3.1"
description = "A discord bot for the Kusogaki discord server"
authors = ["Kusogaki"]
license = "GPL-3.0-or-later"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
discord-py = "^2.4.0"
python-dotenv = "^1.0.1"
redis = "^5.2.1"
sqlalchemy = "^2.0.36"
psycopg2-binary = "^2.9.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.3"
pre-commit = "^4.0.1"
poetry-plugin-export = "^1.8.0"

[tool.poetry.scripts]
lint = "scripts.ruff:lint"
format = "scripts.ruff:format"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.format]
quote-style = "single"
line-ending = "auto"

[tool.ruff.lint]
select = ["F", "E", "I"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["kusogaki-bot"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]